
whitelist = {
    # banking query tools
    "get_iban",
    "get_balance",
    "get_most_recent_transactions",
    "get_scheduled_transactions",
    "read_file",
    "get_user_info",
    # slack query tools
    "get_channels",
    "read_channel_messages",
    "read_inbox",
    "get_users_in_channel",
    "get_webpage",
    # travel query tools
    "get_user_information",
    "get_all_hotels_in_city",
    "get_hotels_prices",
    "get_rating_reviews_for_hotels",
    "get_hotels_address",
    "get_all_restaurants_in_city",
    "get_cuisine_type_for_restaurants",
    "get_restaurants_address",
    "get_rating_reviews_for_restaurants",  
    "get_dietary_restrictions_for_all_restaurants",
    "get_contact_information_for_restaurants",
    "get_price_for_restaurants",
    "check_restaurant_opening_hours",
    "get_all_car_rental_companies_in_city",
    "get_car_types_available",
    "get_rating_reviews_for_car_rental",
    "get_car_fuel_options",
    "get_car_rental_address",
    "get_car_price_per_day",
    "search_calendar_events",
    "get_day_calendar_events",
    "get_flight_information",
    # workspace query tools
    "get_unread_emails",
    "get_sent_emails",
    "get_received_emails",
    "get_draft_emails",
    "search_emails",
    "search_contacts_by_name",
    "search_contacts_by_email",
    "get_current_day",
    "search_files_by_filename",
    "get_file_by_id",
    "list_files",
    "search_files",
}